[tool.poetry]
name = "web-cleaning-app"
packages = [
    { include = "cleaning" },
]
version = "0.1.0"
description = "A fauna & flora data cleaning web application."
authors = ["Salima RAKASS"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.3.3"
numpy = "2.2.6"
flask = "^3.1.2"
pyyaml = "^6.0.3"
openpyxl = "^3.1.5"
unidecode = "^1.4.0"
gunicorn = "^23.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
