#####################
### Gunicorn settings
#####################

gun_num_workers=4
gun_host=0.0.0.0
gun_port=8092
gun_timeout=60

####################
### Python settings
####################

venv_dir=.venv
# L'atlas est compatible avec Python 3, préferez donc l'utilisation de Python 3.X
# python_executable=/usr/bin/python3
PYTHONPATH="$PYTHONPATH:$(pwd)"